title: WriteBar
description: Distraction-free text editor.
show_downloads: true
github:
  zip_url: ./dist/WriteBar.dmgexample
  issues_url: https://github.com/alexander-shvets/writebar/issues
theme: jekyll-theme-minimal
